name: Deploy

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Ref or tag to deploy"
        required: true
        default: "main"

permissions:
  contents: read

jobs:
  deploy-server:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /opt/purrmadeath
            sudo -u purrmadeath git fetch origin --tags
            sudo -u purrmadeath git reset --hard ${{ inputs.ref }}
            sudo -u purrmadeath npm install --include=dev
            sudo systemctl restart purrmadeath-server
            echo "=== Server updated ==="
            sudo systemctl status purrmadeath-server --no-pager -l
